# Generated by Django 3.2.25 on 2024-12-05 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200420_2333'),
        ('student', '0004_student_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentreponse',
            options={},
        ),
        migrations.RemoveField(
            model_name='studentreponse',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='studentreponse',
            name='is_True',
        ),
        migrations.RemoveField(
            model_name='studentreponse',
            name='reponse',
        ),
        migrations.AddField(
            model_name='studentreponse',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentreponse',
            name='response_text',
            field=models.TextField(default='Pas de réponse'),
        ),
        migrations.AlterField(
            model_name='studentreponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='studentreponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='student.student'),
        ),
    ]
