# Generated by Django 2.2.12 on 2024-12-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='responses',
            field=models.TextField(),
        ),
    ]
