# Generated by Django 2.2.12 on 2024-12-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20241224_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
