# Generated by Django 2.2.12 on 2024-12-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='responses',
            field=models.TextField(default='{}'),
        ),
    ]
