# Generated by Django 2.2.12 on 2024-12-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20241224_1710'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
