# Generated by Django 2.2.12 on 2024-12-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_delete_quizresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='coefficient',
            field=models.IntegerField(),
        ),
    ]
