# Generated by Django 2.2.12 on 2024-12-24 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('quiz', '0007_auto_20241224_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='coefficient',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('responses', models.TextField(default='{}')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quiz.Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='student.Student')),
            ],
            options={
                'verbose_name': 'Résultat de Quiz',
                'verbose_name_plural': 'Résultats de Quiz',
                'ordering': ['-date_submitted'],
            },
        ),
    ]
