# Generated by Django 2.2.12 on 2024-12-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20241224_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='coefficient',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
