# Generated by Django 2.2.12 on 2024-12-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20241224_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='coefficient',
            field=models.IntegerField(default=1),
        ),
    ]
