# Generated by Django 2.2.12 on 2024-12-27 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_auto_20241227_1651'),
        ('quiz', '0016_auto_20241226_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='questionresponse',
            options={'verbose_name': 'Réponse de Question', 'verbose_name_plural': 'Réponses de Questions'},
        ),
        migrations.AlterModelOptions(
            name='quizresult',
            options={'ordering': ['-completed_at'], 'verbose_name': 'Résultat du Quiz', 'verbose_name_plural': 'Résultats des Quizs'},
        ),
        migrations.AlterModelOptions(
            name='reponse',
            options={'verbose_name': 'Réponse', 'verbose_name_plural': 'Réponses'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='cours',
            field=models.ForeignKey(help_text='Cours associé au quiz.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_cours', to='school.Cours'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='chapitre',
            field=models.ForeignKey(help_text='Chapitre associé au devoir.', on_delete=django.db.models.deletion.CASCADE, related_name='devoirs', to='school.Chapitre'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='coefficient',
            field=models.IntegerField(help_text='Coefficient du devoir.'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='dateDebut',
            field=models.DateTimeField(help_text='Date de début du devoir.'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='dateFermeture',
            field=models.DateTimeField(help_text='Date de fermeture du devoir.'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, help_text="Date d'ajout du devoir."),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='date_update',
            field=models.DateTimeField(auto_now=True, help_text='Date de mise à jour du devoir.'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug unique généré pour le devoir.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='status',
            field=models.BooleanField(default=True, help_text='Statut actif ou inactif.'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='sujet',
            field=models.TextField(help_text='Sujet du devoir.', max_length=255),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='support',
            field=models.FileField(blank=True, help_text='Fichier associé au devoir.', null=True, upload_to='fichier/import'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.CharField(default='2024-12-27', help_text='Date de création du quiz.', max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, help_text="Date d'ajout du quiz."),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date_update',
            field=models.DateTimeField(auto_now=True, help_text='Date de mise à jour du quiz.'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, help_text='Image associée au quiz.', null=True, upload_to='quiz_images/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_instructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug unique généré pour le quiz.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.BooleanField(default=True, help_text='Statut actif ou inactif.'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='temps',
            field=models.IntegerField(help_text='Durée maximale du quiz en minutes.'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='titre',
            field=models.CharField(help_text='Titre du quiz.', max_length=255),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='completion_time',
            field=models.IntegerField(help_text='Temps en secondes'),
        ),
    ]
