# Generated by Django 2.2.12 on 2024-12-27 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20241227_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-date_add'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizs'},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours_quizzes', to='school.Cours', verbose_name='Cours'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Instructeur'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='temps',
            field=models.PositiveIntegerField(verbose_name='Temps (en minutes)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
    ]
