# Generated by Django 2.2.12 on 2024-12-27 16:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20241227_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questionresponse',
            options={'verbose_name': 'Question Response', 'verbose_name_plural': 'Question\xa0Responses'},
        ),
        migrations.AlterModelOptions(
            name='quizresult',
            options={'ordering': ['-completed_at'], 'verbose_name': 'Quiz Result', 'verbose_name_plural': 'Quiz Results'},
        ),
        migrations.AlterModelOptions(
            name='reponse',
            options={'verbose_name': 'Reponse', 'verbose_name_plural': 'Reponses'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='cours',
        ),
        migrations.AlterField(
            model_name='devoir',
            name='chapitre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_chapitre', to='school.Chapitre'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='coefficient',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='dateDebut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='dateFermeture',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='sujet',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='support',
            field=models.FileField(upload_to='fichier/import'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.CharField(default=datetime.date.today, max_length=255),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='completion_time',
            field=models.IntegerField(help_text='Time taken in seconds'),
        ),
    ]
