# Generated by Django 2.2.12 on 2024-12-27 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_auto_20241227_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.CharField(default='2024-12-27', max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='temps',
            field=models.IntegerField(help_text='Durée du quiz en minutes'),
        ),
    ]
