# Generated by Django 2.2.12 on 2024-12-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_chapitre_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitre',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='duree_en_heure',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/chapitres'),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='ressources/cours'),
        ),
    ]
