# Generated by Django 2.2.12 on 2024-12-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_auto_20241227_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitre',
            name='date_debut',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='date_fin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='duree_en_heure',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='image',
            field=models.ImageField(null=True, upload_to='images/chapitres'),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='video',
            field=models.FileField(null=True, upload_to='ressources/cours'),
        ),
    ]
