# Generated by Django 2.2.12 on 2024-12-27 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0009_instructor_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['user__username'], 'verbose_name': 'Instructeur', 'verbose_name_plural': 'Instructeurs'},
        ),
        migrations.AlterField(
            model_name='instructor',
            name='adresse',
            field=models.CharField(help_text="Adresse de l'instructeur.", max_length=255),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='bio',
            field=models.TextField(default='Votre bio', help_text="Courte biographie de l'instructeur."),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='classe',
            field=models.ForeignKey(blank=True, help_text="Classe assignée à l'instructeur.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_classe', to='school.Classe'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='contact',
            field=models.CharField(help_text="Informations de contact de l'instructeur (email, téléphone, etc.).", max_length=255),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, help_text="Date d'ajout de l'instructeur."),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='date_update',
            field=models.DateTimeField(auto_now=True, help_text="Date de la dernière mise à jour de l'instructeur."),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='matieres',
            field=models.ManyToManyField(blank=True, help_text="Liste des matières enseignées par l'instructeur.", related_name='instructors', to='school.Matiere'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='photo',
            field=models.ImageField(help_text="Photo de profil de l'instructeur.", upload_to='images/Instructor'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='questions',
            field=models.ManyToManyField(blank=True, help_text="Questions créées ou associées à l'instructeur.", related_name='instructeur', to='quiz.Question'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='slug',
            field=models.SlugField(blank=True, help_text="Slug unique généré automatiquement pour l'instructeur.", null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='status',
            field=models.BooleanField(default=True, help_text="Statut actif ou inactif de l'instructeur."),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(help_text='Utilisateur associé à cet instructeur.', on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
