# Generated by Django 2.2.12 on 2024-12-27 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0010_auto_20241227_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructors'},
        ),
        migrations.AlterField(
            model_name='instructor',
            name='adresse',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='bio',
            field=models.TextField(default='Votre bio'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_classe', to='school.Classe'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='matieres',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='school.Matiere'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='photo',
            field=models.ImageField(upload_to='images/Instructor'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='instructeur', to='quiz.Question'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
