# Generated by Django 2.2.12 on 2024-12-27 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20241220_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auteur_message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salon',
            name='nom',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
