# Generated by Django 2.2.12 on 2024-12-27 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20241227_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auteur_message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salon',
            name='nom',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
